### ISSUE TITLE
webengine_kiosk: unexpected exit from port: 8

### ISSUE THREAD

**Issue by epinault** [fhunleth/webengine_kiosk#12] opened 2018-09-10 00:54 UTC
I am trying to redo the training during the conference on a project from scratch and I am hitting this issue

```
00:47:45.481 [error] webengine_kiosk: unexpected exit from port: 8

00:47:45.630 [error] GenServer Display terminating
** (stop) :unexpected_exit
Last message: {#Port<0.34>, {:exit_status, 8}}
State: %{homepage: "file:///srv/erlang/lib/webengine_kiosk-0.2.4/priv/www/index.html", port: #Port<0.34>}

00:47:45.766 [error] webengine_kiosk: unexpected exit from port: 8

00:47:45.767 [error] GenServer Display terminating
** (stop) :unexpected_exit
Last message: {#Port<0.46>, {:exit_status, 8}}
State: %{homepage: "file:///srv/erlang/lib/webengine_kiosk-0.2.4/priv/www/index.html", port: #Port<0.46>}

00:47:45.995 [error] webengine_kiosk: unexpected exit from port: 8

00:47:45.996 [error] GenServer Display terminating
** (stop) :unexpected_exit
Last message: {#Port<0.50>, {:exit_status, 8}}
State: %{homepage: "file:///srv/erlang/lib/webengine_kiosk-0.2.4/priv/www/index.html", port: #Port<0.50>}

00:47:46.035 [error] webengine_kiosk: unexpected exit from port: 8

00:47:46.037 [error] GenServer Display terminating
** (stop) :unexpected_exit
Last message: {#Port<0.59>, {:exit_status, 8}}
State: %{homepage: "file:///srv/erlang/lib/webengine_kiosk-0.2.4/priv/www/index.html", port: #Port<0.59>}

```

What does that mean? What am I missing or doing wrong?

**Comment by epinault** [comment] 2018-10-28 22:06
I am still getting this error and would love to get some help

**Comment by fhunleth** [comment] 2018-10-29 00:56
Sorry - I'm not sure how I missed your first issue. I'm not actively using `webengine_kiosk` right now. Maybe @mobileoverlord has seen this. If not, could you post a link to repository that shows this error and the commands that you ran? I assume that it can't be much more than `mix deps.get` and `mix firmware`, but if I could walk through your steps, then I'll have a better chance of reproducing it.

**Comment by epinault** [comment] 2018-10-30 18:29
this is likely related to options I was passing in the config. I will try to dig more into it but once I removed some of the specified config options it went away

**Comment by fhunleth** [comment] 2019-09-27 14:20
I'm not sure whether this issue was due to building in the source directory, but that's possible based on similar issues I've seen in other projects. Going to close since #20 is now merged and this is getting old.

**Closed as completed by fhunleth** 2019-09-27 14:20 UTC
